[package]
name = "defuse-test-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
poa = []
defuse = []
escrow = []
wallet = []

[dependencies]
defuse-randomness.workspace = true
defuse-crypto = { workspace = true, features = [
    "arbitrary",
    "ed25519",
    "secp256k1",
    "p256",
] }

arbitrary.workspace = true
derive_more = { workspace = true, features = ["full"] }
hex.workspace = true
rand_chacha.workspace = true
rstest.workspace = true
