[package]
name = "defuse-test-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
defuse-crypto ={ workspace = true, features = ["arbitrary"] }
defuse-escrow-swap.workspace = true
defuse-randomness.workspace = true
defuse-token-id.workspace = true

arbitrary.workspace = true
derive_more = { workspace = true, features = ["full"] }
hex.workspace = true
near-sdk.workspace = true
rand_chacha.workspace = true
rstest.workspace = true
