[package]
name = "defuse-test-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
defuse-randomness.workspace = true
defuse-crypto.workspace = true

arbitrary.workspace = true
derive_more = { workspace = true, features = ["full"] }
hex.workspace = true
near-sdk.workspace = true
rand_chacha.workspace = true
rstest.workspace = true
