[package]
name = "defuse-escrow-proxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
defuse-admin-utils.workspace = true
defuse-auth-call.workspace = true
defuse-controller.workspace = true
defuse-crypto = { workspace = true, features = ["serde"] }
defuse-deadline.workspace = true
defuse-borsh-utils.workspace = true
defuse-fees.workspace = true
defuse-near-utils.workspace = true
defuse-nep245.workspace = true
defuse-token-id = { workspace = true, default-features = false, features = ["nep141", "nep245"] }
defuse-transfer-auth.workspace = true
serde_json.workspace = true

near-plugins.workspace = true
near-sdk = { workspace = true, features = ["unstable"] }
serde_with.workspace = true

[dev-dependencies]
defuse-sandbox.workspace = true
defuse-transfer-auth = { workspace = true, features = ["test-utils"] }
multi-token-receiver-stub = { path = "../tests/contracts/multi-token-receiver-stub", features = ["test-utils"] }
impl-tools.workspace = true
near-sdk = { workspace = true, features = ["unstable", "unit-testing"] }
near-workspaces.workspace = true
tokio.workspace = true
serde_json.workspace = true
futures.workspace = true
anyhow.workspace = true

[features]
contract = []
abi = ["defuse-crypto/abi", "defuse-token-id/abi", "defuse-deadline/abi", "defuse-transfer-auth/abi"]
