[package]
name = "defuse-escrow-proxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
defuse-controller.workspace = true
defuse-escrow-swap = { workspace = true, optional = true }
defuse-near-utils.workspace = true
defuse-nep245.workspace = true
defuse-token-id.workspace = true
defuse-oneshot-condvar = { workspace = true, features = ["auth-call"] }

near-contract-standards.workspace = true
near-sdk = { workspace = true, features = ["unstable", "deterministic-account-ids"] }

[dev-dependencies]
# Dependencies needed for examples only
defuse = { workspace = true, features = ["sandbox"] }
defuse-core.workspace = true
defuse-crypto.workspace = true
defuse-sandbox = { workspace = true, features = ["escrow-swap"] }
anyhow.workspace = true
futures.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[features]
default = ["nep141", "nep245", "escrow-swap"]

contract = []
escrow-swap = ["dep:defuse-escrow-swap"]
nep141 = ["defuse-token-id/nep141"]
nep245 = ["defuse-token-id/nep245"]

abi = ["defuse-token-id/abi", "defuse-oneshot-condvar/abi", "defuse-escrow-swap?/abi"]

[[example]]
name = "escrow-swap-demo"
