[package]
name = "defuse-nep413"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[features]
near-api = ["dep:near-api"]

[dependencies]
defuse-crypto = { workspace = true, default-features = false, features = [
    "ed25519",
] }
defuse-near-utils.workspace = true
defuse-nep461.workspace = true
defuse-serde-utils.workspace = true

impl-tools.workspace = true
near-sdk.workspace = true

near-api = { workspace = true, optional = true }

[lints]
workspace = true
