[package]
name = "defuse-deadline"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
abi = ["defuse-borsh-utils/schema"]

[dependencies]
defuse-borsh-utils = { workspace = true, features = ["chrono"] }
defuse-near-utils = { workspace = true, features = ["time"] }
defuse-num-utils.workspace = true

near-sdk.workspace = true
chrono = { workspace = true, features = ["serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = { workspace = true, features = ["serde", "now"] }
