name: Release

on:
  release:
    types: [created]

jobs:
  build_and_upload_reproducible:
    name: Build and Upload Reproducible Contract
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to upload assets to release
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install cargo-near
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.17.0/cargo-near-installer.sh | sh
        
      - name: Build Reproducible WASM
        run: cargo build-all reproducible

      - name: Upload WASM to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          file: res/*
          file_glob: true
          overwrite: true
